CREATE DATABASE IF NOT EXISTS cloud;
USE cloud;
CREATE TABLE IF NOT EXISTS images (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  created_at TIMESTAMP,
  location VARCHAR(255) NOT NULL
);
